# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   annotations:
#     argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
#     argocd.argoproj.io/sync-options: PruneLast=false
#     argocd.argoproj.io/sync-wave: "-2"
#   creationTimestamp: null
#   name: test-project
#   namespace: argocd
# spec:
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   description: sre-team project
#   destinations:
#   - namespace: '*'
#     server: '*'
#   namespaceResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   sourceRepos:
#   - '*'
# status: {}
# ---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: test
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/test/**/local/config.json
      repoURL: https://github.com/iltarsia/test.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata:
          name: '{{ userGivenName }}-local'
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  syncPolicy:
      applicationsSync: create-update
      preserveResourcesOnDeletion: true
    template:
      metadata:
        name: '{{ userGivenName }}'
        namespace: argocd
        labels:
          app.kubernetes.io/name: '{{ appName }}'
      spec:
        destination:
          namespace: '{{ destNamespace }}'
          server: '{{ destServer }}'
        ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
          - /status
          kind: Application
        project: test
        source:
          repoURL: '{{ srcRepoURL }}'
          targetRevision: '{{ srcTargetRevision }}'
          path: '{{ srcPath }}'
        syncPolicy:
          automated:
            allowEmpty: true
            prune: false
            selfHeal: false
          syncOptions:
          - CreateNamespace={{ CreateNamespace }}
status: {}
